### PR TITLE
Update poison to use >= 1.4.0, so that the latest poison can be used

### LINKED ISSUE #215: Poison dependency out of date
The current version of poison is 3.0.  Updating to allow for 3.0 will ease integration.

### PR DESCRIPTION
**Pull request by joshuataylor**
This also updates the other dependencies to their latest versions as
well.

Closes #215.

Let me know if `>=` is the correct syntax to use, as: `~> 1.4 or ~> 2.0 or ~> 3.0` doesn't seem to work.

### CODE REVIEW

**Comment by alanpeabody** [comment]
Thanks @joshuataylor, TBH I am sure we could drop 1.x support for poison without problems, but this is great for now!

**Comment by alanpeabody** [comment]
Actually, it looks like bumping ecto broke the elixir 1.2 test suite, anyway you could revert that update to the lock file (should still work for users)?

**Comment by joshuataylor** [comment]
Okay, I removed the mix.lock changes, as this should be in a followup issue :)

I then ran `mix deps.update poison`, which didn't change the lock file:
```
Running dependency resolution...
Dependency resolution completed:
  poison 1.5.2
```

So I'm guessing that if you rely on poison 3.0 or above, it should work fine.

**Comment by alanpeabody** [comment]
Yup, wonderful, thanks!

**Pull request merged**
